config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  resource :timeline, only: [:show]
  resource :timelinelike, only: [:show]

  resource :profile, only: [:show, :edit, :update]

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
    resources :followings, only: [:index]
    resources :followers, only: [:index]
  end


  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resource :timeline, only: [:show]
    resource :likes, only: [:show, :create, :destroy] 
    resources :comments, only: [:index, :show, :new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/devise.rb
Devise.setup do |config|
  config.mailer_sender = 'please-change-me-at-config-initializers-devise@example.com'
  require 'devise/orm/active_record'  

  ・・・
  config.scoped_views = true
  ・・・

end

app/models/post.rb
class Post < ApplicationRecord

  validates :pictures, presence: true
  validates :content, presence: true

  has_many_attached :pictures

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end


def like_count
  likes.count
end

app/models/user.rb
class User < ApplicationRecord

  validates :email, uniqueness: true
  validates :username, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following

  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  has_one :profile, dependent: :destroy
  has_one_attached :userimage

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.userimage&.attached?
      profile.userimage
    else
      'f_f_object_105_s512_f_object_105_1bg.png'
    end
  end

  def follow!(user)
    user_id = get_user_id(user)
    following_relationships.create!(following_id: user_id)
  end

  def has_followed?(user)
    following_relationships.exists?(following_id: user.id)
  end

  def unfollow!(user)
    user_id = get_user_id(user)

    relation = following_relationships.find_by!(following_id: user_id)
    relation.destroy!
  end

  def hasliked?(post)
    likes.exists?(post_id: post.id)
  end

  def following_count
    followings.count
  end

  def follower_count
    followers.count
  end

  private
  def get_user_id(user)
    if user.is_a?(User)
      user.id
    else
      user
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render 'home/index'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build

    @comments = @post.comments
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save!
      redirect_to posts_path, notice: '投稿できました'
    else
      flash.now[:error] = '投稿できませんでした'
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy!
    redirect_to posts_path, notice: '削除に成功しました'
  end

  private
  def post_params
    params.require(:post).permit(:content, pictures: [])
  end

end

app/controllers/profiles_controller.rb
class  ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile = current_user.profile
    @profile_build = current_user.build_profile
  end

  def edit
    @profile_build = current_user.build_profile
  end

  def update
    @profile_build = current_user.build_profile(profile_params)
    if @profile_build.save
      redirect_to profile_path, notice: 'プロフィール更新'
    else
      flash.now[:error] = '更新できませんでした'
      render :show
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :userimage
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%p わいわい

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PostPicApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    .wrapper
      %p.notice= notice
      %p.alert= alert
      = yield

      %footer
        .footer-container
          = link_to image_tag('ホーム.png'), root_path , class: 'footer-icon', data: {"turbolinks" => false}
          = link_to image_tag('星.png'), timelinelike_path , class: 'footer-icon', data: {"turbolinks" => false}
          = link_to image_tag('プラス.png'), new_post_path , class: 'footer-icon'
          = link_to image_tag('人物.png'), profile_path, class: 'footer-icon'
          = link_to image_tag('ログアウト'), destroy_user_session_path, data: {method: 'DELETE'}, class: 'footer-icon'

  %br
  %br

//= link_to image_tag('プラス.png'), new_post_path, class: 'new_post_icon'

app/views/layouts/layout/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PostPicApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/posts/index.html.haml
.container 
  .timeline_container
  %h4 New Posts
  = link_to 'Timeline', timeline_path, class: 'text-black-50'
  %br
  = link_to 'Popular Posts', timelinelike_path, class: 'text-black-50'

  = render 'commons/posts'

  //= link_to image_tag('プラス.png'), new_post_path, class: 'new_post_icon'
  %br
  

  = javascript_pack_tag 'post'

app/views/posts/new.html.haml
.container
  = form_with model: @post do |f|
    .post-user-icon
      = image_tag 'f_f_object_105_s512_f_object_105_1bg.png'
    .post-username
      %p= current_user.username
    %div 
      = f.text_field :content, placeholder: "What's on your mind ?", class: 'post_content_form'
    %div 
      = f.label :pictures, "+ Album", class: 'picture_input_btn w-100' do
        %i.picture_form_name + Album
        = f.file_field :pictures, multiple: true, class: 'picture_form'
    %div 
    = f.submit 'POST', class: 'btn btn-secondary w-100 mt-4' 

app/views/posts/show.html.haml
.container
  .comment_page_header
    .back_icon
      = link_to image_tag('矢印.png'), :back
    %p.comment-page-title Comment
  .comment#post-show{data:{post_id: @post.id}}
    .comments-container
    
  .comment-set
    .comment-text-area
      = text_area_tag :comment_content, '', class: 'sm w-100',size: '1x1'
    .btn-secondary.btn.w-100.add-comment-btn
      COMMENT

%br
%br
        

  = javascript_pack_tag 'post'

app/views/profiles/show.html.haml
.container
  .user_name
    = current_user.username
  %br
  .user-icon
    - if current_user.userimage.attached?
      = image_tag current_user.userimage
    - else 
      = image_tag 'f_f_object_105_s512_f_object_105_1bg.png'

  .image-upload
    = form_with(model: @profile_build, url: profile_path, method: 'patch', local: true) do |f|
      = f.file_field :userimage
      %br
      = f.submit '保存', class: 'btn btn-outline-secondary btn-avatar-submit'

  .account_status
    .post_count
      .figure-1
        %p= current_user.posts.count
      %p.status-text Posts
    .following_count
      = link_to account_followings_path(current_user.id) do
        .figure-2
          %p= current_user.following_count
        %p.status-text following
    .follower_count
      = link_to account_followers_path(current_user.id) do
        .figure-3
          %p= current_user.follower_count
        %p.status-text Followers

  .img-container-top
    - current_user.posts.each do |post|
      - post.pictures.each do |picture|
        .img-container
          = image_tag picture, class: 'box'